datafactory/urls.py
from django.urls import path

from datafactory import views

app_name = 'datafactory'
urlpatterns = [
    path('<int:tool_id>/', views.detail, name="detail"),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:tool_id>/tool', views.create_data, name="tool"),

]

django_datafactory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('datafactory/', include('datafactory.urls')),
    path('', include('datafactory.urls')),
]

datafactory/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
import datetime


# python3 manage.py makemigrations --empty polls 删除已生成的表信息
# python3 manage.py makemigrations 为模型的改变生成迁移文件
# python3 manage.py migrate 来应用数据库迁移

class Tool(models.Model):
    # 每条语句单独执行，不能加逗号，否则会和下句连续执行，哎好久不用脑子都糊涂了额
    """
    数据工具模型
    """
    tool_name = models.CharField(max_length=200)
    create_time = models.DateTimeField('Create time')

    def __str__(self):
        return self.tool_name

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.create_time <= now


# 注意ToolAttr再自动创建对象时会被转为toolattr 而非 tool_Attr
class ToolAttr(models.Model):
    """
    数据工具属性模型
    attr_describe 属性描述
    attr_value 属性值
    attr_type 属性类型
    attr_remark
    """
    tool = models.ForeignKey(Tool, on_delete=models.CASCADE)
    attr_describe = models.CharField(max_length=200)
    attr_value = models.CharField(blank=True, max_length=200)
    attr_type_choices = [
        (0, 'text'),
        (1, 'number'),
        (2, 'date'),
        (3, 'tel'),
        (4, 'time'),
        (5, 'datetime'),
        (6, 'email'),
        (7, 'datetime-local'),
    ]
    attr_type = models.IntegerField(choices=attr_type_choices, default=0)
    attr_remark = models.CharField(blank=True, max_length=200)

    def __str__(self):
        return self.attr_describe

    def __str__(self):
        return self.attr_value


class ToolPath(models.Model):
    tool = models.ForeignKey(Tool, on_delete=models.CASCADE)
    tool_path = models.CharField(max_length=200)

    def __str__(self):
        return self.tool_path

datafactory/views.py
from django.shortcuts import render, get_object_or_404
from django.http import *
from urllib.parse import urlencode

# Create your views here.
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from datafactory.models import ToolAttr, Tool
from django_datafactory.utils import get_host_ip


class IndexView(generic.ListView):
    template_name = 'datafactory/index.html'
    context_object_name = 'latest_tool_list'

    def get_queryset(self):
        return Tool.objects.filter(create_time__lte=timezone.now()).order_by('-create_time')[:9]


class ResultView(generic.DetailView):
    model = Tool
    template_name = 'datafactory/results.html'


def create_data(request, tool_id):
    tool = get_object_or_404(Tool, pk=tool_id)
    i = 1
    tmp = {}
    while request.POST.get("param" + str(i)) is not None:
        tmp["param" + str(i)] = request.POST.get("param" + str(i))
        i = i + 1
    querystring = urlencode(tmp)
    toolpath = tool.toolpath_set.all()
    print(toolpath[0])
    print(querystring)

    # HOST = get_host_ip()
    # if HOST == '10.0.0.0':
    SERVER_HOST = "120.0.0.0"
    # else:
    #     SERVER_HOST = HOST
    return HttpResponseRedirect("http://%s:8088%s?%s" % (SERVER_HOST,
                                                         toolpath[0], querystring))


def detail(request, tool_id):
    tool = get_object_or_404(Tool, pk=tool_id)
    print(tool.toolattr_set.all())
    return render(request, 'datafactory/detail.html', {"tool": tool, })


class ResultView(generic.DetailView):
    model = Tool
    template_name = 'datafactory/results.html'

datafactory/templates/datafactory/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tool</title>
    {% load static %}
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
	<link rel="stylesheet" type="text/css" href='{% static "datafactory/css/default.css" %}'>
	<style>
    html,body{
    width: 100%;
    height: 100%;
}

    .help-block.error {
      margin-bottom: 5px;
    }
    		.htmleaf-header{
            padding: 1em 190px 1em;
            letter-spacing: -1px;
            text-align: center;
        }
    .col-sm-5{
<!--     max-width: 200px;-->
     margin-left: 300px;
    }
  </style>
</head>
<body>
<div class="main">
    <header class="htmleaf-header">
       <h1>{{tool.tool_name}}</h1>
    </header>

    {% if error_message %}
    <p>
        <strong>
            {{ error_message }}
        </strong>
    </p>
    {% endif %}
    <form   class="form-horizontal" action="/datafactory/{{ tool.id }}/tool" method="post"  >
        {% csrf_token %}
        {% for toolattr  in tool.toolattr_set.all  %}

        <div class="form-group">
        <label class="col-sm-2 control-label" for={{toolattr.get_attr_type_display}}>
            {{ toolattr.attr_describe }}
        </label>
<!--    param{{forloop.counter}}循环生成name    -->
        <div class="col-sm-5">
            <input id={{toolattr.get_attr_type_display}} class="form-control"  type={{toolattr.get_attr_type_display}} name=param{{forloop.counter}} required="required" placeholder={{toolattr.attr_remark}}><br>
        </div>
            <div class="col-sm-5 messages"></div>
        </div>
        {% endfor %}
        <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <input type="submit" class="btn btn-default" value="Submit">
        </div>
      </div>
    </form>
    </div>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.2/underscore-min.js"></script>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
	  <script src=""></script>
    <script src='{% static "datafactory/js/validate.js" %}'></script>
	  <script>
    (function() {
      // These are the constraints used to validate the form
      var constraints = {
        email: {
          // Email is required
          presence: true,
          // and must be an email (duh)
          email: true
        },
        password: {
          // Password is also required
          presence: true,
          // And must be at least 5 characters long
          length: {
            minimum: 5
          }
        },
        "confirm-password": {
          // You need to confirm your password
          presence: true,
          // and it needs to be equal to the other password
          equality: {
            attribute: "password",
            message: "^The passwords does not match"
          }
        },
        username: {
          // You need to pick a username too
          presence: true,
          // And it must be between 3 and 20 characters long
          length: {
            minimum: 3,
            maximum: 20
          },
          format: {
            // We don't allow anything that a-z and 0-9
            pattern: "[a-z0-9]+",
            // but we don't care if the username is uppercase or lowercase
            flags: "i",
            message: "can only contain a-z and 0-9"
          }
        },
        birthdate: {
          // The user needs to give a birthday
          presence: true,
          // and must be born at least 18 years ago
          date: {
            latest: moment().subtract(18, "years"),
            message: "^You must be at least 18 years old to use this service"
          }
        },
        country: {
          // You also need to input where you live
          presence: true,
          // And we restrict the countries supported to Sweden
          inclusion: {
            within: ["SE"],
            // The ^ prevents the field name from being prepended to the error
            message: "^Sorry, this service is for Sweden only"
          }
        },
        zip: {
          // Zip is optional but if specified it must be a 5 digit long number
          format: {
            pattern: "\\d{5}"
          }
        },
        "number-of-children": {
          presence: true,
          // Number of children has to be an integer >= 0
          numericality: {
            onlyInteger: true,
            greaterThanOrEqualTo: 0
          }
        }
      };

      // Hook up the form so we can prevent it from being posted
      var form = document.querySelector("form#main");
      form.addEventListener("submit", function(ev) {
        ev.preventDefault();
        handleFormSubmit(form);
      });

      // Hook up the inputs to validate on the fly
      var inputs = document.querySelectorAll(".form-control")
      for (var i = 0; i < inputs.length; ++i) {
        inputs.item(i).addEventListener("change", function(ev) {
          var errors = validate(form, constraints) || {};
          showErrorsForInput(this, errors[this.name])
        });
      }

      function handleFormSubmit(form, input) {
        // validate the form aainst the constraints
        var errors = validate(form, constraints);
        // then we update the form to reflect the results
        showErrors(form, errors || {});
        if (!errors) {
          showSuccess();
        }
      }

      // Updates the inputs with the validation errors
      function showErrors(form, errors) {
        // We loop through all the inputs and show the errors for that input
        _.each(form.querySelectorAll(".form-control"), function(input) {
          // Since the errors can be null if no errors were found we need to handle
          // that
          showErrorsForInput(input, errors && errors[input.name]);
        });
      }

      // Shows the errors for a specific input
      function showErrorsForInput(input, errors) {
        // This is the root of the input
        console.log(input,'input');
        var formGroup = closestParent(input, "form-group");
        console.log(formGroup,'formGroup')
          // Find where the error messages will be insert into
          var  messages =  formGroup.querySelector(".messages");
        // First we remove any old messages and resets the classes
        resetFormGroup(formGroup);
        // If we have errors
        if (errors) {
          // we first mark the group has having errors
          formGroup.classList.add("has-error");
          // then we append all the errors
          _.each(errors, function(error) {
            addError(messages, error);
          });
        } else {
          // otherwise we simply mark it as success
          formGroup.classList.add("has-success");
        }
      }

      // Recusively finds the closest parent that has the specified class
      function closestParent(child, className) {
      console.log(child,'child')
        if (!child || child == document) {
          return null;
        }
        if (child.classList.contains(className)) {
          return child;
        } else {
          return closestParent(child.parentNode, className);
        }
      }

      function resetFormGroup(formGroup) {
        // Remove the success and error classes
        formGroup.classList.remove("has-error");
        formGroup.classList.remove("has-success");
        // and remove any old messages
        _.each(formGroup.querySelectorAll(".help-block.error"), function(el) {
          el.parentNode.removeChild(el);
        });
      }

      // Adds the specified error with the following markup
      // <p class="help-block error">[message]</p>
      function addError(messages, error) {
        var block = document.createElement("p");
        block.classList.add("help-block");
        block.classList.add("error");
        block.innerText = error;
        messages.appendChild(block);
      }

      function showSuccess() {
        // We made it \:D/
        alert("Success!");
      }
    })();
  </script>
</body>
</html>

datafactory/templates/datafactory/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
	<style>
		body {
		  color: #fff;
		  font-family: "Rubik", sans-serif;
		}
		.htmleaf-header{
            padding: 1em 190px 1em;
            letter-spacing: -1px;
            text-align: center;
        }
        .htmleaf-header h1 {
            font-weight: 600;
            font-size: 2em;
            line-height: 1;
            margin-bottom: 0;
            color: #2c3e50;
        }
        .htmleaf-header h1 span {
            display: block;
            font-size: 60%;
            font-weight: 400;
            padding: 0.8em 0 0.5em 0;
            color: #2c3e50;
        }

		.item.footer {
		  flex-wrap: wrap;
		  padding: 5rem;
		  text-align: center;
		  font-size: 18px;
		  line-height: 1.7;
		  grid-column: span 1;
		}
		@media screen and (min-width: 823px) and (max-width: 1223px) {
		  .item.footer {
		    grid-column: span 2;
		  }
		}
		.item.footer a {
		  text-decoration: none;
		  color: #fff;
		  padding: 3px 0;
		  border-bottom: 1px dashed;
		}
		.item.footer a:hover {
		  border-bottom: 1px solid;
		}

		footer {
		  margin-top: 1.5rem;
		}
		footer a {
		  text-decoration: none;
		  display: inline-block;
		  width: 45px;
		  height: 45px;
		  border-radius: 50%;
		  background: transparent;
		  border: 1px dashed #fff;
		  color: #fff;
		  margin: 5px;
		}
		footer a:hover {
		  background: rgba(255, 255, 255, 0.1);
		}
		footer a .icons {
		  margin-top: 8px;
		  display: inline-block;
		  font-size: 20px;
		}
		footer a .icons:before {
		  position: relative;
		}

		* {
		  box-sizing: border-box;
		}
		*:before, *:after {
		  content: "";
		  position: absolute;
		}

		.main-content {
		  display: grid;
		  width: 100%;
		  height:100%;
		  grid-template-columns: repeat(auto-fit, minmax(33%, 1fr));
          background:#2c3e50;
		}
		.main-content .item {
		  display: grid;
		  grid-template-rows: 1fr min-content;
		  align-items: center;
		  justify-content: center;
		  height: 50vh;
		  flex-wrap: wrap;
		  background: var(--bg-color);
		}
		.main-content .item:not(.footer) {
		  padding-top: 1rem;
		}

		button {
		  background: transparent;
		  color: #fff;
		  border: 3px solid #fff;
		  border-radius: 50px;
		  padding: 0.8rem 2rem;
		  font: 24px "Margarine", sans-serif;
		  outline: none;
		  cursor: pointer;
		  position: relative;
		  transition: 0.2s ease-in-out;
		  letter-spacing: 2px;
		}

		.name {
		  width: 100%;
		  text-align: center;
		  padding: 0 0 3rem;
		  font: 500 14px 'Rubik', sans-serif;
		  letter-spacing: .5px;
		  text-transform: uppercase;
		  text-shadow: 0 1px 1px rgba(0, 0, 0, 0.4);
		}

		.button__wrapper {
		  display: inline-block;
		  position: relative;
		  width: 200px;
		  height: 65px;
		  display: flex;
		  justify-content: center;
		  align-items: center;
		}

		.button-pulse button {
		  background: var(--bg-color);
		  width: 100%;
		  height: 100%;
		  position: absolute;
		  top: 0;
		  left: 0;
		  z-index: 2;
		}
		.button-pulse .button__wrapper:hover .pulsing:before {
		  animation: pulsing 0.2s linear infinite;
		}
		.button-pulse .button__wrapper:hover .pulsing:after {
		  animation: pulsing1 0.2s linear infinite;
		}

		.pulsing {
		  width: 99%;
		  height: 99%;
		  border-radius: 50px;
		  z-index: 1;
		  position: relative;
		}
		.pulsing:before, .pulsing:after {
		  width: 100%;
		  height: 100%;
		  border: inherit;
		  top: 0;
		  left: 0;
		  z-index: 0;
		  background: #fff;
		  border-radius: inherit;
		  animation: pulsing 2.5s linear infinite;
		}
		.pulsing:after {
		  animation: pulsing1 2.5s linear infinite;
		}

		@keyframes pulsing {
		  0% {
		    opacity: 1;
		    transform: scaleY(1) scaleX(1);
		  }
		  20% {
		    opacity: 0.5;
		  }
		  70% {
		    opacity: 0.2;
		    transform: scaleY(1.8) scaleX(1.4);
		  }
		  80% {
		    opacity: 0;
		    transform: scaleY(1.8) scaleX(1.4);
		  }
		  90% {
		    opacity: 0;
		    transform: scaleY(1) scaleX(1);
		  }
		}
		@keyframes pulsing1 {
		  0% {
		    opacity: 1;
		    transform: scaleY(1) scaleX(1);
		  }
		  20% {
		    opacity: 0.5;
		  }
		  70% {
		    opacity: 0.2;
		    transform: scaleY(1.3) scaleX(1.15);
		  }
		  80% {
		    opacity: 0;
		    transform: scaleY(1.3) scaleX(1.15);
		  }
		  90% {
		    opacity: 0;
		    transform: scaleY(1) scaleX(1);
		  }
		}
		.button-typewriter button {
		  width: 100%;
		  height: 100%;
		}
		.button-typewriter p {
		  animation: typing 4s steps(12) infinite;
		  display: inline-block;
		  overflow: hidden;
		  white-space: nowrap;
		}
		.button-typewriter .button__wrapper:hover p {
		  animation: blink 0.3s infinite;
		}

		@keyframes typing {
		  0% {
		    width: 0;
		  }
		  50% {
		    width: 100%;
		  }
		  55%,
			65%,
			75% {
		    opacity: 1;
		  }
		  60%,
			70% {
		    opacity: 0;
		  }
		  80% {
		    width: 100%;
		  }
		  100% {
		    width: 0;
		  }
		}
		.button-parrot .parrot {
		  position: absolute;
		  width: 60px;
		  text-align: center;
		  animation: blink 0.8s infinite;
		  color: transparent;
		}
		.button-parrot .parrot:before {
		  content: "Click Me!";
		}
		.button-parrot .parrot:nth-child(1) {
		  top: -30px;
		  left: -40px;
		  font: 12px/1 "Margarine", sans-serif;
		  transform: rotate(-20deg);
		  animation-duration: 0.5s;
		}
		.button-parrot .parrot:nth-child(2) {
		  font: 12px/1 "Margarine", sans-serif;
		  right: -40px;
		  top: -20px;
		  transform: rotate(15deg);
		  animation-duration: 0.3s;
		}
		.button-parrot .parrot:nth-child(3) {
		  font: 16px/1 "Margarine", sans-serif;
		  top: -60px;
		  left: 15px;
		  transform: rotate(10deg);
		  animation-duration: 1s;
		}
		.button-parrot .parrot:nth-child(4) {
		  font: 18px/1 "Margarine", sans-serif;
		  top: -70px;
		  left: 95px;
		  transform: rotate(2deg);
		  animation-duration: 0.7s;
		}
		.button-parrot .parrot:nth-child(5) {
		  font: 14px/1 "Margarine", sans-serif;
		  top: 80px;
		  left: 105px;
		  transform: rotate(-10deg);
		  animation-duration: 0.8s;
		}
		.button-parrot .parrot:nth-child(6) {
		  font: 12px/1 "Margarine", sans-serif;
		  top: 80px;
		  left: 5px;
		  transform: rotate(10deg);
		  animation-duration: 1.2s;
		}
		.button-parrot button:hover .parrot:before {
		  content: "Do it!";
		  width: 70px;
		}

		@keyframes blink {
		  25%,
			75% {
		    color: transparent;
		  }
		  40%,
			60% {
		    color: #fff;
		  }
		}
		.button-hand button:before {
		  content: "👇";
		  font-size: 60px;
		  transform: scaleX(-1);
		  right: 0px;
		  top: -68px;
		  animation: up-down 1s infinite;
		}
		.button-hand button .hands:before, .button-hand button .hands:after {
		  content: "👇";
		  font-size: 40px;
		  opacity: 0;
		  transition: 0.4s ease-in-out;
		}
		.button-hand button .hands:before {
		  transform: rotate(-60deg);
		  left: -45px;
		  top: -10px;
		}
		.button-hand button .hands:after {
		  transform: rotate(170deg);
		  right: 30px;
		  top: 50px;
		}
		.button-hand button:hover .hands:before {
		  opacity: 1;
		  left: -35px;
		}
		.button-hand button:hover .hands:after {
		  opacity: 1;
		  top: 40px;
		}

		@keyframes up-down {
		  50% {
		    margin-top: -20px;
		  }
		}
		.button-100 .emoji {
		  position: absolute;
		  top: -45px;
		  left: 0;
		  width: 35px;
		  height: 35px;
		  overflow: hidden;
		}
		.button-100 .emoji:before {
		  content: "💯";
		  display: inline-block;
		  animation: give-score 2.5s infinite;
		  position: relative;
		  top: 0;
		}
		.button-100 .emoji:nth-child(2) {
		  left: 0;
		  right: 0;
		  margin: auto;
		}
		.button-100 .emoji:nth-child(2):before {
		  animation: give-score 2.5s infinite 0.2s;
		}
		.button-100 .emoji:nth-child(3) {
		  left: auto;
		  right: 0;
		}
		.button-100 .emoji:nth-child(3):before {
		  animation: give-score 2.5s infinite 0.4s;
		}
		.button-100 button:hover .emoji:before {
		  content: "👏";
		  transition: 0.5s ease;
		}

		@keyframes give-score {
		  30%,
			80% {
		    top: 0;
		  }
		  40%,
			70% {
		    top: 50px;
		  }
		}
		.button-pressure marquee {
		  position: absolute;
		  width: 90%;
		  top: 125%;
		  left: 5%;
		  font: 18px/1 "Margarine", sans-serif;
		}
		.button-pressure marquee span {
		  display: inline-block;
		  height: 20px;
		}
		.button-pressure marquee span:not(:last-child) {
		  margin-right: 130px;
		}
		.button-pressure button:before {
		  content: "OMG YAS";
		  transition: 0.5s ease;
		  left: 0;
		  right: 0;
		  margin: auto;
		  top: -15px;
		  font-size: 12px;
		  opacity: 0;
		}
		.button-pressure button:hover:before {
		  animation: omg-yes 1s;
		}

		.button-rainbow button {
		  animation: rainbow 3s infinite, heartbeat 0.6s infinite;
		  background: #c0392b;
		}
		.button-rainbow button .rainbow {
		  width: 120px;
		  height: 120px;
		  border-radius: 50%;
		  position: absolute;
		  left: 0;
		  right: 0;
		  margin: auto;
		  top: -40px;
		  transition: 0.5s ease;
		  opacity: 0;
		  transform: rotate(0);
		}
		.button-rainbow button .rainbow:before {
		  content: "🌈";
		  left: 0;
		}
		.button-rainbow button:hover .rainbow {
		  opacity: 1;
		  animation: rotate-nonstop 0.2s infinite;
		}
		.button-rainbow button + .name {
		  color: #444;
		}

		@keyframes rotate-nonstop {
		  50% {
		    transform: rotate(92deg);
		  }
		}
		@keyframes omg-yes {
		  50% {
		    opacity: 1;
		  }
		  100% {
		    top: -50px;
		  }
		}
		@keyframes rainbow {
		  0% {
		    background: #1abc9c;
		  }
		  10% {
		    background: #2ecc71;
		  }
		  20% {
		    background: #3498db;
		  }
		  30% {
		    background: #9b59b6;
		  }
		  40% {
		    background: #e74c3c;
		  }
		  50% {
		    background: #e67e22;
		  }
		  60% {
		    background: #f1c40f;
		  }
		  70% {
		    background: #2c3e50;
		  }
		  80% {
		    background: #9b59b6;
		  }
		}
		.button-jittery button {
		  animation: jittery 4s infinite;
		}
		.button-jittery button:hover {
		  animation: heartbeat 0.2s infinite;
		}

		@keyframes jittery {
		  5%,
			50% {
		    transform: scale(1);
		  }
		  10% {
		    transform: scale(0.9);
		  }
		  15% {
		    transform: scale(1.15);
		  }
		  20% {
		    transform: scale(1.15) rotate(-5deg);
		  }
		  25% {
		    transform: scale(1.15) rotate(5deg);
		  }
		  30% {
		    transform: scale(1.15) rotate(-3deg);
		  }
		  35% {
		    transform: scale(1.15) rotate(2deg);
		  }
		  40% {
		    transform: scale(1.15) rotate(0);
		  }
		}
		@keyframes heartbeat {
		  50% {
		    transform: scale(1.1);
		  }
		}
	</style>
</head>
<body>
<div class="htmleaf-container">
    <header class="htmleaf-header">
       <h1>数据工厂 <span> Xiao mai data factory</span></h1>
    </header>
    {% if latest_tool_list%}
    <div class="main-content">
        {% for tool in latest_tool_list %}
        <div class="item button-parrot" style="--bg-color: #2c3e50;">
            <a href="{% url 'datafactory:detail' tool.id%}">
                <button>
                    {{tool.tool_name}}
              <div class="parrot"></div>
		      <div class="parrot"></div>
		      <div class="parrot"></div>
		      <div class="parrot"></div>
		      <div class="parrot"></div>
		      <div class="parrot"></div>
            </button>
            </a>
        </div>
         {% endfor %}
    </div>
    {% else %}
     <p>no tools are available!</p>
        <a href="http://10.0.4.55:8000/admin">去添加>></a>
    {% endif %}
    <div style="color: #2c3e50; text-align:center;margin-top: 20px; margin-bottom: 20px; font-size:15px;">
        Copyright ©  xiao mai team of QA 🌈  备案号：闽ICP备88888888号-8

    </div>
</div>
</body>
</html>

datafactory/templates/datafactory/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>results</title>
</head>
<body>
<h1>{{tool.tool_name}}</h1>
<ul>
    {% for toolattr in tool.toolattr_set.all %}
    <li>
        {{toolattr.attr_describe}}--{{toolattr.attr_value }}
    </li>
    {% endfor %}
</ul>
<a href="{% url 'datafactory:detail' tool.id %}">需要再次创建吗？</a>
</body>
</html>